#!/usr/bin/env bash

sudo -v

echo "Installing Xcode Command Line Tools."
xcode-select --install

defaults write com.apple.Finder AppleShowAllFiles true
killall Finder

echo "Installing homebrew..."
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew upgrade -all

echo "Installing zsh..."
brew install zsh zsh-history-substring-search zsh-autosuggestions zsh-syntax-highlighting wget

echo "Installing git..."
brew install git

echo "Installing node..."
brew install node
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash

echo "Installing yarn..."
brew install yarn

echo "Installing python..."
brew install python
brew install python3

echo "Install software..."
brew cask install --appdir="/Applications" google-chrome
brew cask install --appdir="/Applications" visual-studio-code
# brew cask install --appdir="/Applications" docker
brew cask install --appdir="/Applications" spotify
brew cask install --appdir="/Applications" station
brew cask install --appdir="/Applications" ubar

echo "Setup hyper..."
brew cask install --appdir="/Applications" hyperterm
npm install -g spaceship-prompt
wget -O ~/.zshrc https://raw.githubusercontent.com/alanuecker/dotfiles/master/shell/.zshrc
wget -O ~/.hyper.js https://raw.githubusercontent.com/alanuecker/dotfiles/master/shell/.hyper.js

echo "Setup karabiner..."
brew cask install --appdir="/Applications" karabiner-elements
wget -O ~/.config/karabiner/karabiner.json https://raw.githubusercontent.com/alanuecker/dotfiles/master/keyboard/karabiner/karabiner.json
wget -O ~/Library/Fonts https://github.com/alanuecker/dotfiles/raw/master/shell/patched/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf
