#!/usr/bin/env bash

sudo -v

echo "Installing Xcode Command Line Tools."
xcode-select --install

defaults write com.apple.Finder AppleShowAllFiles true
killall Finder

echo "Installing homebrew..."
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew upgrade -all

echo "Installing zsh..."
brew install wget
brew install fzf
brew install neovim
brew install zsh zsh-history-substring-search zsh-autosuggestions zsh-syntax-highlighting
wget -O ~/.zshrc https://raw.githubusercontent.com/alanuecker/dotfiles/main/shell/.zshrc
wget -O ~/.config/zsh/git.zsh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/lib/git.zsh
wget -O ~/.config/zsh/git.plugin.zsh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/git/git.plugin.zsh


echo "Installing git..."
brew install git

echo "Installing node..."
brew install node
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

echo "Installing yarn..."
brew install yarn

echo "Installing python..."
brew install pyenv

echo "Install enhancd..."
brew isntall fzy
cd ~
wget -qO- https://raw.githubusercontent.com/b4b4r07/enhancd

echo "Setup karabiner..."
brew cask install --appdir="/Applications" karabiner-elements
wget -O ~/.config/karabiner/karabiner.json https://raw.githubusercontent.com/alanuecker/dotfiles/master/keyboard/karabiner/karabiner.json

echo "Install software..."
brew cask install --appdir="/Applications" google-chrome
brew cask install --appdir="/Applications" visual-studio-code
brew cask install --appdir="/Applications" spotify
brew cask install --appdir="/Applications" arc
brew cask install --appdir="/Applications" notion
brew cask install --appdir="/Applications" slack
brew cask install --appdir="/Applications" docker